### ISSUE TITLE
Any plans for open-sourcing？

### ISSUE THREAD

**Issue by Tweakzx** [pkusys/TGS#1]
Hello,

I'm interested in the progress of the open source code for TGS. I noticed that there hasn't been any recent activity on the repository and I was wondering if there are any plans for further development.

**Comment by grgalex** [comment]
I have just released `nvshare`, a transparent GPU sharing mechanism **without memory size constraints** for bare-metal and Kubernetes, based on my diploma thesis.

It is also based on Unified Memory.

- With `nvshare` you can concurrently run multiple processes/containers on the same GPU safely, each process/container having the **whole physical GPU memory available**.
- `nvshare` doesn't impose any memory limit for containers and respects security (unlike for example MPS), as each container runs in its own CUDA context, unchanged.

You can find it at https://github.com/grgalex/nvshare.
